name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.3.0

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - run: pnpm install

      - run: pnpm run test

      - run: pnpm run lint

      - run: pnpm run typecheck

      - run: pnpm run build
